Job model interface in ts
Visual-Testing-for-Android-Apps/backend pull request #16
Opened 2021-08-23 12:25 UTC by beining00

Add the job Model interface to `postProcessHandler` and `uploadHandler`

2021-08-23 12:28 UTC, YinghaoMa approved these changes

2021-08-23 13:01 UTC, mt-empty requested changes
Great job, the job model look good.
I only looked at the diff, I didn't pull and test(frankly I wouldn't know how to test it).

2021-08-23 13:37 UTC, beining00 commented on server/postProcessHandler/src/service/jobModel.ts
> +	fileType: FileType;
enum should have it first letter capitalised I guess

2021-08-23 14:09 UTC, mt-empty commented on server/postProcessHandler/src/service/jobModel.ts
> +	fileType: FileType;
Ok, I think `fileStatus` should also be capitalized

2021-08-24 09:33 UTC, teva0003 approved these changes

2021-08-24 09:59 UTC, mt-empty approved these changes

2021-08-25 10:02 UTC, reteppeter commented on server/postProcessHandler/src/service/jobModel.ts
> +export interface job {
These interfaces don't have the type information that DynamoDB returns/uses (AttributeValue).

2021-09-13 06:12 UTC, closed without merging