Feature/josh/split video
Visual-Testing-for-Android-Apps/backend pull request #80
Opened 2021-10-15 11:41 UTC by josh-sharp

# 
## Proposed changes

Created Python function which takes an mp4 and outputs images and videos into a directory (to be integrated into a pipeline to submit the images to OwlEyes and Seenomaly)

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

This is a feature which we are not currently integrating into our application. 

If this is to be integrated, uploadHandler would send an mp4 to this function, and then feed the output into jobHandler, and continue with the Live Job/Batch Job pipeline.

2021-10-15 13:31 UTC, reteppeter requested changes

2021-10-15 13:31 UTC, reteppeter commented on server/videoSplit/videoSplitConcept.py
> +    os.makedirs(os.path.dirname(__file__) + "/" + os.path.basename(filename), exist_ok=True)
This should be done using os.path.join (especially as os.path is already being used).

2021-10-16 12:57 UTC, josh-sharp commented on server/videoSplit/videoSplitConcept.py
> +    os.makedirs(os.path.dirname(__file__) + "/" + os.path.basename(filename), exist_ok=True)
Yep absolutely - done now

2021-10-20 13:53 UTC, reteppeter approved these changes

2021-10-23 04:04 UTC, merged